### PR TITLE
Changed BezelImageView.java Canvas Flags

### PR DESCRIPTION
**Pull request by felipecds**
Changed BezelImageView.java Canvas Flags. Suppressed with Canvas.ALL_SAVE_FLAG for Android P compatibility.

Now in Android P, only this flag exist, so trying to pass any other will crash the app.

### CODE REVIEW

**Comment by amatkivskiy** [comment]
@felipecds Thanks for the PR. 
Unfortunately I am no longer supporting this library 😢.  
Do you need this changes to be published to nuget?

**Review by amatkivskiy — APPROVED** [review]

**Comment by felipecds** [comment]
Really not, because I build myself and applied to my project. But it will help others with this problem. But if you give me the rights, I can build a nuget version from this and publish.

**Comment by illomi7** [comment]
Hi, is possible to publish this PR on nuget?
Thank you very much.

**Comment by amatkivskiy** [comment]
@illomi7 @felipecds Unfortunately, this repo is no longer maintained. Please use forks for this.

**Pull request closed without merging**
